FROM ghcr.io/charmbracelet/vhs:v0.11.0@sha256:9d5fc3dc0c160b0fb1d2212baff07e6bdf3fa9438c504a3237484567302fcf93

COPY dist/git-harvest /usr/local/bin/git-harvest
RUN chmod +x /usr/local/bin/git-harvest
